fixed chr call in create-chroot. Gave chr a sliver of a brain by prepending CHROOTDIRS in case provided dir couldn't be located

diff --git a/chr b/chr
--- a/chr
+++ b/chr
@@ -11,7 +11,17 @@ function main {
 		usage
 		exit 0
 	fi
-	TARGET=${CHROOTDIRS}/$1
+	if [ -d $1 ]; then
+		TARGET=$1
+	else
+		if [ -d ${CHROOTDIRS}/$1 ]; then
+			TARGET=${CHROOTDIRS}/$1
+		else
+			echo "cannot locate $1"
+			exit 1
+		fi
+	fi	
+
 
 	echo "* binding /dev, /sys, /tmp and /proc"
 	for mp in ${MOUNTS}; do
diff --git a/create-chroot b/create-chroot
--- a/create-chroot
+++ b/create-chroot
@@ -14,6 +14,15 @@ if [ "$#" -lt 2 ]; then
 	exit 1
 fi
 
+CHR=`which chr`
+if [ -z "$CHR" ]; then
+	if [ -x ./chr ]; then
+		CHR="./chr"
+	else
+		echo "cannot find 'chr' executable."
+		exit 1
+	fi
+fi
 
 CHROOTDIRS="/root/devel/chroots"
 BASE="/var/cache/pbuilder/"
@@ -65,7 +74,7 @@ fi
 echo "* chrooting into environment"
 sleep 1
 echo 
-./chr $DEST
+chr $DEST
 echo
 
 
